namespace Generalate.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class addCommanPropertiesallTables : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.AllProvinceRecords", "CreatedBy", c => c.String());
            AddColumn("dbo.AllProvinceRecords", "CreatedDate", c => c.String());
            AddColumn("dbo.AllProvinceRecords", "UpdateBy", c => c.String());
            AddColumn("dbo.AllProvinceRecords", "UpdateDate", c => c.String());
            AddColumn("dbo.AppointmentDatas", "CreatedBy", c => c.String());
            AddColumn("dbo.AppointmentDatas", "CreatedDate", c => c.String());
            AddColumn("dbo.AppointmentDatas", "UpdateBy", c => c.String());
            AddColumn("dbo.AppointmentDatas", "UpdateDate", c => c.String());
            AddColumn("dbo.Appointments", "CreatedBy", c => c.String());
            AddColumn("dbo.Appointments", "CreatedDate", c => c.String());
            AddColumn("dbo.Appointments", "UpdateBy", c => c.String());
            AddColumn("dbo.Appointments", "UpdateDate", c => c.String());
            AddColumn("dbo.Circulars", "CreatedBy", c => c.String());
            AddColumn("dbo.Circulars", "CreatedDate", c => c.String());
            AddColumn("dbo.Circulars", "UpdateBy", c => c.String());
            AddColumn("dbo.Circulars", "UpdateDate", c => c.String());
            AddColumn("dbo.ComHouses", "CreatedBy", c => c.String());
            AddColumn("dbo.ComHouses", "CreatedDate", c => c.String());
            AddColumn("dbo.ComHouses", "UpdateBy", c => c.String());
            AddColumn("dbo.ComHouses", "UpdateDate", c => c.String());
            AddColumn("dbo.ComHouseDetails", "CreatedBy", c => c.String());
            AddColumn("dbo.ComHouseDetails", "CreatedDate", c => c.String());
            AddColumn("dbo.ComHouseDetails", "UpdateBy", c => c.String());
            AddColumn("dbo.ComHouseDetails", "UpdateDate", c => c.String());
            AddColumn("dbo.ComOutSides", "CreatedBy", c => c.String());
            AddColumn("dbo.ComOutSides", "CreatedDate", c => c.String());
            AddColumn("dbo.ComOutSides", "UpdateBy", c => c.String());
            AddColumn("dbo.ComOutSides", "UpdateDate", c => c.String());
            AddColumn("dbo.ComOutSideDetails", "CreatedBy", c => c.String());
            AddColumn("dbo.ComOutSideDetails", "CreatedDate", c => c.String());
            AddColumn("dbo.ComOutSideDetails", "UpdateBy", c => c.String());
            AddColumn("dbo.ComOutSideDetails", "UpdateDate", c => c.String());
            AddColumn("dbo.CongDatas", "CreatedBy", c => c.String());
            AddColumn("dbo.CongDatas", "UpdateBy", c => c.String());
            AddColumn("dbo.CongDatas", "UpdateDate", c => c.String());
            AddColumn("dbo.CongreDatas", "CreatedBy", c => c.String());
            AddColumn("dbo.CongreDatas", "UpdateBy", c => c.String());
            AddColumn("dbo.CongreDatas", "UpdateDate", c => c.String());
            AddColumn("dbo.CounCircCommis", "CreatedBy", c => c.String());
            AddColumn("dbo.CounCircCommis", "CreatedDate", c => c.String());
            AddColumn("dbo.CounCircCommis", "UpdateBy", c => c.String());
            AddColumn("dbo.CounCircCommis", "UpdateDate", c => c.String());
            AddColumn("dbo.DataListItems", "CreatedBy", c => c.String());
            AddColumn("dbo.DataListItems", "CreatedDate", c => c.String());
            AddColumn("dbo.DataListItems", "UpdateBy", c => c.String());
            AddColumn("dbo.DataListItems", "UpdateDate", c => c.String());
            AddColumn("dbo.DataListItems2", "CreatedBy", c => c.String());
            AddColumn("dbo.DataListItems2", "CreatedDate", c => c.String());
            AddColumn("dbo.DataListItems2", "UpdateBy", c => c.String());
            AddColumn("dbo.DataListItems2", "UpdateDate", c => c.String());
            AddColumn("dbo.DataLists", "CreatedBy", c => c.String());
            AddColumn("dbo.DataLists", "CreatedDate", c => c.String());
            AddColumn("dbo.DataLists", "UpdateBy", c => c.String());
            AddColumn("dbo.DataLists", "UpdateDate", c => c.String());
            AddColumn("dbo.DataLists2", "CreatedBy", c => c.String());
            AddColumn("dbo.DataLists2", "CreatedDate", c => c.String());
            AddColumn("dbo.DataLists2", "UpdateBy", c => c.String());
            AddColumn("dbo.DataLists2", "UpdateDate", c => c.String());
            AddColumn("dbo.ExcelSheetDatas", "CreatedBy", c => c.String());
            AddColumn("dbo.ExcelSheetDatas", "CreatedDate", c => c.String());
            AddColumn("dbo.ExcelSheetDatas", "UpdateBy", c => c.String());
            AddColumn("dbo.ExcelSheetDatas", "UpdateDate", c => c.String());
            AddColumn("dbo.FamilyDetails", "CreatedBy", c => c.String());
            AddColumn("dbo.FamilyDetails", "CreatedDate", c => c.String());
            AddColumn("dbo.FamilyDetails", "UpdateBy", c => c.String());
            AddColumn("dbo.FamilyDetails", "UpdateDate", c => c.String());
            AddColumn("dbo.GeneralateFileNoes", "CreatedBy", c => c.String());
            AddColumn("dbo.GeneralateFileNoes", "CreatedDate", c => c.String());
            AddColumn("dbo.GeneralateFileNoes", "UpdateBy", c => c.String());
            AddColumn("dbo.GeneralateFileNoes", "UpdateDate", c => c.String());
            AddColumn("dbo.GeneralCouncils", "CreatedBy", c => c.String());
            AddColumn("dbo.GeneralCouncils", "CreatedDate", c => c.String());
            AddColumn("dbo.GeneralCouncils", "UpdateBy", c => c.String());
            AddColumn("dbo.GeneralCouncils", "UpdateDate", c => c.String());
            AddColumn("dbo.MyComDataCHes", "CreatedBy", c => c.String());
            AddColumn("dbo.MyComDataCHes", "CreatedDate", c => c.String());
            AddColumn("dbo.MyComDataCHes", "UpdateBy", c => c.String());
            AddColumn("dbo.MyComDataCHes", "UpdateDate", c => c.String());
            AddColumn("dbo.MyDataCOS", "CreatedBy", c => c.String());
            AddColumn("dbo.MyDataCOS", "CreatedDate", c => c.String());
            AddColumn("dbo.MyDataCOS", "UpdateBy", c => c.String());
            AddColumn("dbo.MyDataCOS", "UpdateDate", c => c.String());
            AddColumn("dbo.NewsLetters", "CreatedBy", c => c.String());
            AddColumn("dbo.NewsLetters", "CreatedDate", c => c.String());
            AddColumn("dbo.NewsLetters", "UpdateBy", c => c.String());
            AddColumn("dbo.NewsLetters", "UpdateDate", c => c.String());
            AddColumn("dbo.ProvinceDatas", "CreatedBy", c => c.String());
            AddColumn("dbo.ProvinceDatas", "UpdateBy", c => c.String());
            AddColumn("dbo.ProvinceDatas", "UpdateDate", c => c.String());
            AddColumn("dbo.RolePermissions", "CreatedBy", c => c.String());
            AddColumn("dbo.RolePermissions", "CreatedDate", c => c.String());
            AddColumn("dbo.RolePermissions", "UpdateBy", c => c.String());
            AddColumn("dbo.RolePermissions", "UpdateDate", c => c.String());
            AddColumn("dbo.Sacraments", "CreatedBy", c => c.String());
            AddColumn("dbo.Sacraments", "CreatedDate", c => c.String());
            AddColumn("dbo.Sacraments", "UpdateBy", c => c.String());
            AddColumn("dbo.Sacraments", "UpdateDate", c => c.String());
            AddColumn("dbo.SocietyDatas", "CreatedBy", c => c.String());
            AddColumn("dbo.SocietyDatas", "UpdateBy", c => c.String());
            AddColumn("dbo.SocietyDatas", "UpdateDate", c => c.String());
            AddColumn("dbo.Societys", "CreatedBy", c => c.String());
            AddColumn("dbo.Societys", "CreatedDate", c => c.String());
            AddColumn("dbo.Societys", "UpdateBy", c => c.String());
            AddColumn("dbo.Societys", "UpdateDate", c => c.String());
            AddColumn("dbo.SocInsPages", "CreatedBy", c => c.String());
            AddColumn("dbo.SocInsPages", "CreatedDate", c => c.String());
            AddColumn("dbo.SocInsPages", "UpdateBy", c => c.String());
            AddColumn("dbo.SocInsPages", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_Academy", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_Academy", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_Academy", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_Academy", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_Archive", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_Archive", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_Archive", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_Archive", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_Bank_Details", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_Bank_Details", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_Bank_Details", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_Bank_Details", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_BookOfAccountsDoc", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_BookOfAccountsDoc", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_BookOfAccountsDoc", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_BookOfAccountsDoc", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_CandidatesInformationDoc", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_CandidatesInformationDoc", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_CandidatesInformationDoc", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_CandidatesInformationDoc", "UpdateDate", c => c.String());
            AddColumn("dbo.Tbl_Comm", "CreatedBy", c => c.String());
            AddColumn("dbo.Tbl_Comm", "UpdateBy", c => c.String());
            AddColumn("dbo.Tbl_Comm", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_CommonDataList", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_CommonDataList", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_CommonDataList", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_CommonDataList", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_CommonDataListItems", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_CommonDataListItems", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_CommonDataListItems", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_CommonDataListItems", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_CommunicationOfficeDoc", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_CommunicationOfficeDoc", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_CommunicationOfficeDoc", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_CommunicationOfficeDoc", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_CommunitiesSocialCentresDoc", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_CommunitiesSocialCentresDoc", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_CommunitiesSocialCentresDoc", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_CommunitiesSocialCentresDoc", "UpdateDate", c => c.String());
            AddColumn("dbo.Tbl_Complains", "CreatedBy", c => c.String());
            AddColumn("dbo.Tbl_Complains", "CreatedDate", c => c.String());
            AddColumn("dbo.Tbl_Complains", "UpdateBy", c => c.String());
            AddColumn("dbo.Tbl_Complains", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_Complaint", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_Complaint", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_Complaint", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_Complaint", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_ConfreresDoc", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_ConfreresDoc", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_ConfreresDoc", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_ConfreresDoc", "UpdateDate", c => c.String());
            AddColumn("dbo.Tbl_Cong", "CreatedBy", c => c.String());
            AddColumn("dbo.Tbl_Cong", "UpdateBy", c => c.String());
            AddColumn("dbo.Tbl_Cong", "UpdateDate", c => c.String());
            AddColumn("dbo.Tbl_CongrationsData", "CreatedBy", c => c.String());
            AddColumn("dbo.Tbl_CongrationsData", "UpdateBy", c => c.String());
            AddColumn("dbo.Tbl_CongrationsData", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_Congregation", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_Congregation", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_Congregation", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_Diocese", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_Diocese", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_Diocese", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_Diocese", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_DioceseData", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_DioceseData", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_DioceseData", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_DioceseData", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_EmergencyContact", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_EmergencyContact", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_EmergencyContact", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_EmergencyContact", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_PersonalDetails", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_PersonalDetails", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_PersonalDetails", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_PersonalDetails", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_Entry", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_Entry", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_Entry", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_Entry", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_EntryLife", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_EntryLife", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_EntryLife", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_EntryLife", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_EntryLife1", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_EntryLife1", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_EntryLife1", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_EntryLife1", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_FinancialGuidelineDoc", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_FinancialGuidelineDoc", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_FinancialGuidelineDoc", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_FinancialGuidelineDoc", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_FinancialReportDoc", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_FinancialReportDoc", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_FinancialReportDoc", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_FinancialReportDoc", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_FomDoc", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_FomDoc", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_FomDoc", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_FomDoc", "UpdateDate", c => c.String());
            AddColumn("dbo.Tbl_formationsDetails", "CreatedBy", c => c.String());
            AddColumn("dbo.Tbl_formationsDetails", "CreatedDate", c => c.String());
            AddColumn("dbo.Tbl_formationsDetails", "UpdateBy", c => c.String());
            AddColumn("dbo.Tbl_formationsDetails", "UpdateDate", c => c.String());
            AddColumn("dbo.Tbl_FormationTypes", "CreatedBy", c => c.String());
            AddColumn("dbo.Tbl_FormationTypes", "CreatedDate", c => c.String());
            AddColumn("dbo.Tbl_FormationTypes", "UpdateBy", c => c.String());
            AddColumn("dbo.Tbl_FormationTypes", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_FormatorsMeetDoc", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_FormatorsMeetDoc", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_FormatorsMeetDoc", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_FormatorsMeetDoc", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_FundRaisingCommiteeDoc", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_FundRaisingCommiteeDoc", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_FundRaisingCommiteeDoc", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_FundRaisingCommiteeDoc", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_GeneralateDoc", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_GeneralateDoc", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_GeneralateDoc", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_GeneralateDoc", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_GeneralMattersDoc", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_GeneralMattersDoc", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_GeneralMattersDoc", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_GeneralMattersDoc", "UpdateDate", c => c.String());
            AddColumn("dbo.Tbl_Governer", "CreatedBy", c => c.String());
            AddColumn("dbo.Tbl_Governer", "CreatedDate", c => c.String());
            AddColumn("dbo.Tbl_Governer", "UpdateBy", c => c.String());
            AddColumn("dbo.Tbl_Governer", "UpdateDate", c => c.String());
            AddColumn("dbo.Tbl_GovernerSoc", "CreatedBy", c => c.String());
            AddColumn("dbo.Tbl_GovernerSoc", "CreatedDate", c => c.String());
            AddColumn("dbo.Tbl_GovernerSoc", "UpdateBy", c => c.String());
            AddColumn("dbo.Tbl_GovernerSoc", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_Health", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_Health", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_Health", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_HomeLiveAndHomeVisit", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_HomeLiveAndHomeVisit", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_HomeLiveAndHomeVisit", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_HomeLiveAndHomeVisit", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_Inst", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_Inst", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_Inst", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_Inst", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_InstDetails", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_InstDetails", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_InstDetails", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_InstDetails", "UpdateDate", c => c.String());
            AddColumn("dbo.Tbl_Institution", "CreatedBy", c => c.String());
            AddColumn("dbo.Tbl_Institution", "UpdateBy", c => c.String());
            AddColumn("dbo.Tbl_Institution", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_institution123", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_institution123", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_institution123", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_institution123", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_InstitutionFinal", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_InstitutionFinal", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_InstitutionFinal", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_InstitutionFinal", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_Insurance", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_Insurance", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_Insurance", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_Insurance", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_Jubilee", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_Jubilee", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_Jubilee", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_Jubilee", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_KnownLanguages", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_KnownLanguages", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_KnownLanguages", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_KnownLanguages", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_LandDetails", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_LandDetails", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_LandDetails", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_LandDetails", "UpdateDate", c => c.String());
            AddColumn("dbo.Tbl_LandDocuments", "CreatedBy", c => c.String());
            AddColumn("dbo.Tbl_LandDocuments", "UpdateBy", c => c.String());
            AddColumn("dbo.Tbl_LandDocuments", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_LivingOutsideTheCongregation", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_LivingOutsideTheCongregation", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_LivingOutsideTheCongregation", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_LivingOutsideTheCongregation", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_MinistryDoc", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_MinistryDoc", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_MinistryDoc", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_MinistryDoc", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_MissionDoc", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_MissionDoc", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_MissionDoc", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_MissionDoc", "UpdateDate", c => c.String());
            AddColumn("dbo.MultiLanguages", "CreatedBy", c => c.String());
            AddColumn("dbo.MultiLanguages", "UpdateBy", c => c.String());
            AddColumn("dbo.MultiLanguages", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_OngoingFormationDoc", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_OngoingFormationDoc", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_OngoingFormationDoc", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_OngoingFormationDoc", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_OVCDoc", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_OVCDoc", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_OVCDoc", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_OVCDoc", "UpdateDate", c => c.String());
            AddColumn("dbo.Tbl_Paris", "CreatedBy", c => c.String());
            AddColumn("dbo.Tbl_Paris", "UpdateBy", c => c.String());
            AddColumn("dbo.Tbl_Paris", "UpdateDate", c => c.String());
            AddColumn("dbo.Tbl_ParisInstitutionDetails", "CreatedBy", c => c.String());
            AddColumn("dbo.Tbl_ParisInstitutionDetails", "UpdateBy", c => c.String());
            AddColumn("dbo.Tbl_ParisInstitutionDetails", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_Passed", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_Passed", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_Passed", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_Passed", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_Primarydetails", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_Primarydetails", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_Primarydetails", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_Primarydetails", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_Province", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_Province", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_Province", "UpdateDate", c => c.String());
            AddColumn("dbo.Tbl_ProvinceCouncil", "CreatedBy", c => c.String());
            AddColumn("dbo.Tbl_ProvinceCouncil", "CreatedDate", c => c.String());
            AddColumn("dbo.Tbl_ProvinceCouncil", "UpdateBy", c => c.String());
            AddColumn("dbo.Tbl_ProvinceCouncil", "UpdateDate", c => c.String());
            AddColumn("dbo.Tbl_provinceData", "CreatedBy", c => c.String());
            AddColumn("dbo.Tbl_provinceData", "UpdateBy", c => c.String());
            AddColumn("dbo.Tbl_provinceData", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_ProvincialDoc", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_ProvincialDoc", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_ProvincialDoc", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_ProvincialDoc", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_ReligiousEducation", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_ReligiousEducation", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_ReligiousEducation", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_ReligiousEducation", "UpdateDate", c => c.String());
            AddColumn("dbo.Tbl_RenewalVows", "CreatedBy", c => c.String());
            AddColumn("dbo.Tbl_RenewalVows", "CreatedDate", c => c.String());
            AddColumn("dbo.Tbl_RenewalVows", "UpdateBy", c => c.String());
            AddColumn("dbo.Tbl_RenewalVows", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_Retirement", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_Retirement", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_Retirement", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_Retirement", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_SCTDoc", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_SCTDoc", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_SCTDoc", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_SCTDoc", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_SecularEducation", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_SecularEducation", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_SecularEducation", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_SecularEducation", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_Seminar", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_Seminar", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_Seminar", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_Seminar", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_SeperationFromTheCongregation", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_SeperationFromTheCongregation", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_SeperationFromTheCongregation", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_SeperationFromTheCongregation", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_ServiceInTheCongregation", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_ServiceInTheCongregation", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_ServiceInTheCongregation", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_ServiceInTheCongregation", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_Soc_Addminstration", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_Soc_Addminstration", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_Soc_Addminstration", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_Soc_Addminstration", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_SocialInstitutionDoc", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_SocialInstitutionDoc", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_SocialInstitutionDoc", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_SocialInstitutionDoc", "UpdateDate", c => c.String());
            AddColumn("dbo.Tbl_SocietyDetails", "CreatedBy", c => c.String());
            AddColumn("dbo.Tbl_SocietyDetails", "CreatedDate", c => c.String());
            AddColumn("dbo.Tbl_SocietyDetails", "UpdateBy", c => c.String());
            AddColumn("dbo.Tbl_SocietyDetails", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_Socityadd", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_Socityadd", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_Socityadd", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_Socityadd", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_SpiritualCommunityDoc", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_SpiritualCommunityDoc", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_SpiritualCommunityDoc", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_SpiritualCommunityDoc", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_StCamillusProvincialateDoc", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_StCamillusProvincialateDoc", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_StCamillusProvincialateDoc", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_StCamillusProvincialateDoc", "UpdateDate", c => c.String());
            AddColumn("dbo.Tbl_Transfer", "CreatedBy", c => c.String());
            AddColumn("dbo.Tbl_Transfer", "UpdateBy", c => c.String());
            AddColumn("dbo.Tbl_Transfer", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_TravelRecord", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_TravelRecord", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_TravelRecord", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_TravelRecord", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_unknow", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_unknow", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_unknow", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_unknow", "UpdateDate", c => c.String());
            AddColumn("dbo.Tbl_UserLogins", "UpdateBy", c => c.String());
            AddColumn("dbo.Tbl_UserLogins", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_UserModuleLogin", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_UserModuleLogin", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_UserModuleLogin", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_UserModuleLogin", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_VocationalTrainingDoc", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_VocationalTrainingDoc", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_VocationalTrainingDoc", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_VocationalTrainingDoc", "UpdateDate", c => c.String());
            AddColumn("dbo.tbl_VocationPromotionDoc", "CreatedBy", c => c.String());
            AddColumn("dbo.tbl_VocationPromotionDoc", "CreatedDate", c => c.String());
            AddColumn("dbo.tbl_VocationPromotionDoc", "UpdateBy", c => c.String());
            AddColumn("dbo.tbl_VocationPromotionDoc", "UpdateDate", c => c.String());
        }
        
        public override void Down()
        {
            DropColumn("dbo.tbl_VocationPromotionDoc", "UpdateDate");
            DropColumn("dbo.tbl_VocationPromotionDoc", "UpdateBy");
            DropColumn("dbo.tbl_VocationPromotionDoc", "CreatedDate");
            DropColumn("dbo.tbl_VocationPromotionDoc", "CreatedBy");
            DropColumn("dbo.tbl_VocationalTrainingDoc", "UpdateDate");
            DropColumn("dbo.tbl_VocationalTrainingDoc", "UpdateBy");
            DropColumn("dbo.tbl_VocationalTrainingDoc", "CreatedDate");
            DropColumn("dbo.tbl_VocationalTrainingDoc", "CreatedBy");
            DropColumn("dbo.tbl_UserModuleLogin", "UpdateDate");
            DropColumn("dbo.tbl_UserModuleLogin", "UpdateBy");
            DropColumn("dbo.tbl_UserModuleLogin", "CreatedDate");
            DropColumn("dbo.tbl_UserModuleLogin", "CreatedBy");
            DropColumn("dbo.Tbl_UserLogins", "UpdateDate");
            DropColumn("dbo.Tbl_UserLogins", "UpdateBy");
            DropColumn("dbo.tbl_unknow", "UpdateDate");
            DropColumn("dbo.tbl_unknow", "UpdateBy");
            DropColumn("dbo.tbl_unknow", "CreatedDate");
            DropColumn("dbo.tbl_unknow", "CreatedBy");
            DropColumn("dbo.tbl_TravelRecord", "UpdateDate");
            DropColumn("dbo.tbl_TravelRecord", "UpdateBy");
            DropColumn("dbo.tbl_TravelRecord", "CreatedDate");
            DropColumn("dbo.tbl_TravelRecord", "CreatedBy");
            DropColumn("dbo.Tbl_Transfer", "UpdateDate");
            DropColumn("dbo.Tbl_Transfer", "UpdateBy");
            DropColumn("dbo.Tbl_Transfer", "CreatedBy");
            DropColumn("dbo.tbl_StCamillusProvincialateDoc", "UpdateDate");
            DropColumn("dbo.tbl_StCamillusProvincialateDoc", "UpdateBy");
            DropColumn("dbo.tbl_StCamillusProvincialateDoc", "CreatedDate");
            DropColumn("dbo.tbl_StCamillusProvincialateDoc", "CreatedBy");
            DropColumn("dbo.tbl_SpiritualCommunityDoc", "UpdateDate");
            DropColumn("dbo.tbl_SpiritualCommunityDoc", "UpdateBy");
            DropColumn("dbo.tbl_SpiritualCommunityDoc", "CreatedDate");
            DropColumn("dbo.tbl_SpiritualCommunityDoc", "CreatedBy");
            DropColumn("dbo.tbl_Socityadd", "UpdateDate");
            DropColumn("dbo.tbl_Socityadd", "UpdateBy");
            DropColumn("dbo.tbl_Socityadd", "CreatedDate");
            DropColumn("dbo.tbl_Socityadd", "CreatedBy");
            DropColumn("dbo.Tbl_SocietyDetails", "UpdateDate");
            DropColumn("dbo.Tbl_SocietyDetails", "UpdateBy");
            DropColumn("dbo.Tbl_SocietyDetails", "CreatedDate");
            DropColumn("dbo.Tbl_SocietyDetails", "CreatedBy");
            DropColumn("dbo.tbl_SocialInstitutionDoc", "UpdateDate");
            DropColumn("dbo.tbl_SocialInstitutionDoc", "UpdateBy");
            DropColumn("dbo.tbl_SocialInstitutionDoc", "CreatedDate");
            DropColumn("dbo.tbl_SocialInstitutionDoc", "CreatedBy");
            DropColumn("dbo.tbl_Soc_Addminstration", "UpdateDate");
            DropColumn("dbo.tbl_Soc_Addminstration", "UpdateBy");
            DropColumn("dbo.tbl_Soc_Addminstration", "CreatedDate");
            DropColumn("dbo.tbl_Soc_Addminstration", "CreatedBy");
            DropColumn("dbo.tbl_ServiceInTheCongregation", "UpdateDate");
            DropColumn("dbo.tbl_ServiceInTheCongregation", "UpdateBy");
            DropColumn("dbo.tbl_ServiceInTheCongregation", "CreatedDate");
            DropColumn("dbo.tbl_ServiceInTheCongregation", "CreatedBy");
            DropColumn("dbo.tbl_SeperationFromTheCongregation", "UpdateDate");
            DropColumn("dbo.tbl_SeperationFromTheCongregation", "UpdateBy");
            DropColumn("dbo.tbl_SeperationFromTheCongregation", "CreatedDate");
            DropColumn("dbo.tbl_SeperationFromTheCongregation", "CreatedBy");
            DropColumn("dbo.tbl_Seminar", "UpdateDate");
            DropColumn("dbo.tbl_Seminar", "UpdateBy");
            DropColumn("dbo.tbl_Seminar", "CreatedDate");
            DropColumn("dbo.tbl_Seminar", "CreatedBy");
            DropColumn("dbo.tbl_SecularEducation", "UpdateDate");
            DropColumn("dbo.tbl_SecularEducation", "UpdateBy");
            DropColumn("dbo.tbl_SecularEducation", "CreatedDate");
            DropColumn("dbo.tbl_SecularEducation", "CreatedBy");
            DropColumn("dbo.tbl_SCTDoc", "UpdateDate");
            DropColumn("dbo.tbl_SCTDoc", "UpdateBy");
            DropColumn("dbo.tbl_SCTDoc", "CreatedDate");
            DropColumn("dbo.tbl_SCTDoc", "CreatedBy");
            DropColumn("dbo.tbl_Retirement", "UpdateDate");
            DropColumn("dbo.tbl_Retirement", "UpdateBy");
            DropColumn("dbo.tbl_Retirement", "CreatedDate");
            DropColumn("dbo.tbl_Retirement", "CreatedBy");
            DropColumn("dbo.Tbl_RenewalVows", "UpdateDate");
            DropColumn("dbo.Tbl_RenewalVows", "UpdateBy");
            DropColumn("dbo.Tbl_RenewalVows", "CreatedDate");
            DropColumn("dbo.Tbl_RenewalVows", "CreatedBy");
            DropColumn("dbo.tbl_ReligiousEducation", "UpdateDate");
            DropColumn("dbo.tbl_ReligiousEducation", "UpdateBy");
            DropColumn("dbo.tbl_ReligiousEducation", "CreatedDate");
            DropColumn("dbo.tbl_ReligiousEducation", "CreatedBy");
            DropColumn("dbo.tbl_ProvincialDoc", "UpdateDate");
            DropColumn("dbo.tbl_ProvincialDoc", "UpdateBy");
            DropColumn("dbo.tbl_ProvincialDoc", "CreatedDate");
            DropColumn("dbo.tbl_ProvincialDoc", "CreatedBy");
            DropColumn("dbo.Tbl_provinceData", "UpdateDate");
            DropColumn("dbo.Tbl_provinceData", "UpdateBy");
            DropColumn("dbo.Tbl_provinceData", "CreatedBy");
            DropColumn("dbo.Tbl_ProvinceCouncil", "UpdateDate");
            DropColumn("dbo.Tbl_ProvinceCouncil", "UpdateBy");
            DropColumn("dbo.Tbl_ProvinceCouncil", "CreatedDate");
            DropColumn("dbo.Tbl_ProvinceCouncil", "CreatedBy");
            DropColumn("dbo.tbl_Province", "UpdateDate");
            DropColumn("dbo.tbl_Province", "UpdateBy");
            DropColumn("dbo.tbl_Province", "CreatedBy");
            DropColumn("dbo.tbl_Primarydetails", "UpdateDate");
            DropColumn("dbo.tbl_Primarydetails", "UpdateBy");
            DropColumn("dbo.tbl_Primarydetails", "CreatedDate");
            DropColumn("dbo.tbl_Primarydetails", "CreatedBy");
            DropColumn("dbo.tbl_Passed", "UpdateDate");
            DropColumn("dbo.tbl_Passed", "UpdateBy");
            DropColumn("dbo.tbl_Passed", "CreatedDate");
            DropColumn("dbo.tbl_Passed", "CreatedBy");
            DropColumn("dbo.Tbl_ParisInstitutionDetails", "UpdateDate");
            DropColumn("dbo.Tbl_ParisInstitutionDetails", "UpdateBy");
            DropColumn("dbo.Tbl_ParisInstitutionDetails", "CreatedBy");
            DropColumn("dbo.Tbl_Paris", "UpdateDate");
            DropColumn("dbo.Tbl_Paris", "UpdateBy");
            DropColumn("dbo.Tbl_Paris", "CreatedBy");
            DropColumn("dbo.tbl_OVCDoc", "UpdateDate");
            DropColumn("dbo.tbl_OVCDoc", "UpdateBy");
            DropColumn("dbo.tbl_OVCDoc", "CreatedDate");
            DropColumn("dbo.tbl_OVCDoc", "CreatedBy");
            DropColumn("dbo.tbl_OngoingFormationDoc", "UpdateDate");
            DropColumn("dbo.tbl_OngoingFormationDoc", "UpdateBy");
            DropColumn("dbo.tbl_OngoingFormationDoc", "CreatedDate");
            DropColumn("dbo.tbl_OngoingFormationDoc", "CreatedBy");
            DropColumn("dbo.MultiLanguages", "UpdateDate");
            DropColumn("dbo.MultiLanguages", "UpdateBy");
            DropColumn("dbo.MultiLanguages", "CreatedBy");
            DropColumn("dbo.tbl_MissionDoc", "UpdateDate");
            DropColumn("dbo.tbl_MissionDoc", "UpdateBy");
            DropColumn("dbo.tbl_MissionDoc", "CreatedDate");
            DropColumn("dbo.tbl_MissionDoc", "CreatedBy");
            DropColumn("dbo.tbl_MinistryDoc", "UpdateDate");
            DropColumn("dbo.tbl_MinistryDoc", "UpdateBy");
            DropColumn("dbo.tbl_MinistryDoc", "CreatedDate");
            DropColumn("dbo.tbl_MinistryDoc", "CreatedBy");
            DropColumn("dbo.tbl_LivingOutsideTheCongregation", "UpdateDate");
            DropColumn("dbo.tbl_LivingOutsideTheCongregation", "UpdateBy");
            DropColumn("dbo.tbl_LivingOutsideTheCongregation", "CreatedDate");
            DropColumn("dbo.tbl_LivingOutsideTheCongregation", "CreatedBy");
            DropColumn("dbo.Tbl_LandDocuments", "UpdateDate");
            DropColumn("dbo.Tbl_LandDocuments", "UpdateBy");
            DropColumn("dbo.Tbl_LandDocuments", "CreatedBy");
            DropColumn("dbo.tbl_LandDetails", "UpdateDate");
            DropColumn("dbo.tbl_LandDetails", "UpdateBy");
            DropColumn("dbo.tbl_LandDetails", "CreatedDate");
            DropColumn("dbo.tbl_LandDetails", "CreatedBy");
            DropColumn("dbo.tbl_KnownLanguages", "UpdateDate");
            DropColumn("dbo.tbl_KnownLanguages", "UpdateBy");
            DropColumn("dbo.tbl_KnownLanguages", "CreatedDate");
            DropColumn("dbo.tbl_KnownLanguages", "CreatedBy");
            DropColumn("dbo.tbl_Jubilee", "UpdateDate");
            DropColumn("dbo.tbl_Jubilee", "UpdateBy");
            DropColumn("dbo.tbl_Jubilee", "CreatedDate");
            DropColumn("dbo.tbl_Jubilee", "CreatedBy");
            DropColumn("dbo.tbl_Insurance", "UpdateDate");
            DropColumn("dbo.tbl_Insurance", "UpdateBy");
            DropColumn("dbo.tbl_Insurance", "CreatedDate");
            DropColumn("dbo.tbl_Insurance", "CreatedBy");
            DropColumn("dbo.tbl_InstitutionFinal", "UpdateDate");
            DropColumn("dbo.tbl_InstitutionFinal", "UpdateBy");
            DropColumn("dbo.tbl_InstitutionFinal", "CreatedDate");
            DropColumn("dbo.tbl_InstitutionFinal", "CreatedBy");
            DropColumn("dbo.tbl_institution123", "UpdateDate");
            DropColumn("dbo.tbl_institution123", "UpdateBy");
            DropColumn("dbo.tbl_institution123", "CreatedDate");
            DropColumn("dbo.tbl_institution123", "CreatedBy");
            DropColumn("dbo.Tbl_Institution", "UpdateDate");
            DropColumn("dbo.Tbl_Institution", "UpdateBy");
            DropColumn("dbo.Tbl_Institution", "CreatedBy");
            DropColumn("dbo.tbl_InstDetails", "UpdateDate");
            DropColumn("dbo.tbl_InstDetails", "UpdateBy");
            DropColumn("dbo.tbl_InstDetails", "CreatedDate");
            DropColumn("dbo.tbl_InstDetails", "CreatedBy");
            DropColumn("dbo.tbl_Inst", "UpdateDate");
            DropColumn("dbo.tbl_Inst", "UpdateBy");
            DropColumn("dbo.tbl_Inst", "CreatedDate");
            DropColumn("dbo.tbl_Inst", "CreatedBy");
            DropColumn("dbo.tbl_HomeLiveAndHomeVisit", "UpdateDate");
            DropColumn("dbo.tbl_HomeLiveAndHomeVisit", "UpdateBy");
            DropColumn("dbo.tbl_HomeLiveAndHomeVisit", "CreatedDate");
            DropColumn("dbo.tbl_HomeLiveAndHomeVisit", "CreatedBy");
            DropColumn("dbo.tbl_Health", "UpdateDate");
            DropColumn("dbo.tbl_Health", "UpdateBy");
            DropColumn("dbo.tbl_Health", "CreatedBy");
            DropColumn("dbo.Tbl_GovernerSoc", "UpdateDate");
            DropColumn("dbo.Tbl_GovernerSoc", "UpdateBy");
            DropColumn("dbo.Tbl_GovernerSoc", "CreatedDate");
            DropColumn("dbo.Tbl_GovernerSoc", "CreatedBy");
            DropColumn("dbo.Tbl_Governer", "UpdateDate");
            DropColumn("dbo.Tbl_Governer", "UpdateBy");
            DropColumn("dbo.Tbl_Governer", "CreatedDate");
            DropColumn("dbo.Tbl_Governer", "CreatedBy");
            DropColumn("dbo.tbl_GeneralMattersDoc", "UpdateDate");
            DropColumn("dbo.tbl_GeneralMattersDoc", "UpdateBy");
            DropColumn("dbo.tbl_GeneralMattersDoc", "CreatedDate");
            DropColumn("dbo.tbl_GeneralMattersDoc", "CreatedBy");
            DropColumn("dbo.tbl_GeneralateDoc", "UpdateDate");
            DropColumn("dbo.tbl_GeneralateDoc", "UpdateBy");
            DropColumn("dbo.tbl_GeneralateDoc", "CreatedDate");
            DropColumn("dbo.tbl_GeneralateDoc", "CreatedBy");
            DropColumn("dbo.tbl_FundRaisingCommiteeDoc", "UpdateDate");
            DropColumn("dbo.tbl_FundRaisingCommiteeDoc", "UpdateBy");
            DropColumn("dbo.tbl_FundRaisingCommiteeDoc", "CreatedDate");
            DropColumn("dbo.tbl_FundRaisingCommiteeDoc", "CreatedBy");
            DropColumn("dbo.tbl_FormatorsMeetDoc", "UpdateDate");
            DropColumn("dbo.tbl_FormatorsMeetDoc", "UpdateBy");
            DropColumn("dbo.tbl_FormatorsMeetDoc", "CreatedDate");
            DropColumn("dbo.tbl_FormatorsMeetDoc", "CreatedBy");
            DropColumn("dbo.Tbl_FormationTypes", "UpdateDate");
            DropColumn("dbo.Tbl_FormationTypes", "UpdateBy");
            DropColumn("dbo.Tbl_FormationTypes", "CreatedDate");
            DropColumn("dbo.Tbl_FormationTypes", "CreatedBy");
            DropColumn("dbo.Tbl_formationsDetails", "UpdateDate");
            DropColumn("dbo.Tbl_formationsDetails", "UpdateBy");
            DropColumn("dbo.Tbl_formationsDetails", "CreatedDate");
            DropColumn("dbo.Tbl_formationsDetails", "CreatedBy");
            DropColumn("dbo.tbl_FomDoc", "UpdateDate");
            DropColumn("dbo.tbl_FomDoc", "UpdateBy");
            DropColumn("dbo.tbl_FomDoc", "CreatedDate");
            DropColumn("dbo.tbl_FomDoc", "CreatedBy");
            DropColumn("dbo.tbl_FinancialReportDoc", "UpdateDate");
            DropColumn("dbo.tbl_FinancialReportDoc", "UpdateBy");
            DropColumn("dbo.tbl_FinancialReportDoc", "CreatedDate");
            DropColumn("dbo.tbl_FinancialReportDoc", "CreatedBy");
            DropColumn("dbo.tbl_FinancialGuidelineDoc", "UpdateDate");
            DropColumn("dbo.tbl_FinancialGuidelineDoc", "UpdateBy");
            DropColumn("dbo.tbl_FinancialGuidelineDoc", "CreatedDate");
            DropColumn("dbo.tbl_FinancialGuidelineDoc", "CreatedBy");
            DropColumn("dbo.tbl_EntryLife1", "UpdateDate");
            DropColumn("dbo.tbl_EntryLife1", "UpdateBy");
            DropColumn("dbo.tbl_EntryLife1", "CreatedDate");
            DropColumn("dbo.tbl_EntryLife1", "CreatedBy");
            DropColumn("dbo.tbl_EntryLife", "UpdateDate");
            DropColumn("dbo.tbl_EntryLife", "UpdateBy");
            DropColumn("dbo.tbl_EntryLife", "CreatedDate");
            DropColumn("dbo.tbl_EntryLife", "CreatedBy");
            DropColumn("dbo.tbl_Entry", "UpdateDate");
            DropColumn("dbo.tbl_Entry", "UpdateBy");
            DropColumn("dbo.tbl_Entry", "CreatedDate");
            DropColumn("dbo.tbl_Entry", "CreatedBy");
            DropColumn("dbo.tbl_PersonalDetails", "UpdateDate");
            DropColumn("dbo.tbl_PersonalDetails", "UpdateBy");
            DropColumn("dbo.tbl_PersonalDetails", "CreatedDate");
            DropColumn("dbo.tbl_PersonalDetails", "CreatedBy");
            DropColumn("dbo.tbl_EmergencyContact", "UpdateDate");
            DropColumn("dbo.tbl_EmergencyContact", "UpdateBy");
            DropColumn("dbo.tbl_EmergencyContact", "CreatedDate");
            DropColumn("dbo.tbl_EmergencyContact", "CreatedBy");
            DropColumn("dbo.tbl_DioceseData", "UpdateDate");
            DropColumn("dbo.tbl_DioceseData", "UpdateBy");
            DropColumn("dbo.tbl_DioceseData", "CreatedDate");
            DropColumn("dbo.tbl_DioceseData", "CreatedBy");
            DropColumn("dbo.tbl_Diocese", "UpdateDate");
            DropColumn("dbo.tbl_Diocese", "UpdateBy");
            DropColumn("dbo.tbl_Diocese", "CreatedDate");
            DropColumn("dbo.tbl_Diocese", "CreatedBy");
            DropColumn("dbo.tbl_Congregation", "UpdateDate");
            DropColumn("dbo.tbl_Congregation", "UpdateBy");
            DropColumn("dbo.tbl_Congregation", "CreatedBy");
            DropColumn("dbo.Tbl_CongrationsData", "UpdateDate");
            DropColumn("dbo.Tbl_CongrationsData", "UpdateBy");
            DropColumn("dbo.Tbl_CongrationsData", "CreatedBy");
            DropColumn("dbo.Tbl_Cong", "UpdateDate");
            DropColumn("dbo.Tbl_Cong", "UpdateBy");
            DropColumn("dbo.Tbl_Cong", "CreatedBy");
            DropColumn("dbo.tbl_ConfreresDoc", "UpdateDate");
            DropColumn("dbo.tbl_ConfreresDoc", "UpdateBy");
            DropColumn("dbo.tbl_ConfreresDoc", "CreatedDate");
            DropColumn("dbo.tbl_ConfreresDoc", "CreatedBy");
            DropColumn("dbo.tbl_Complaint", "UpdateDate");
            DropColumn("dbo.tbl_Complaint", "UpdateBy");
            DropColumn("dbo.tbl_Complaint", "CreatedDate");
            DropColumn("dbo.tbl_Complaint", "CreatedBy");
            DropColumn("dbo.Tbl_Complains", "UpdateDate");
            DropColumn("dbo.Tbl_Complains", "UpdateBy");
            DropColumn("dbo.Tbl_Complains", "CreatedDate");
            DropColumn("dbo.Tbl_Complains", "CreatedBy");
            DropColumn("dbo.tbl_CommunitiesSocialCentresDoc", "UpdateDate");
            DropColumn("dbo.tbl_CommunitiesSocialCentresDoc", "UpdateBy");
            DropColumn("dbo.tbl_CommunitiesSocialCentresDoc", "CreatedDate");
            DropColumn("dbo.tbl_CommunitiesSocialCentresDoc", "CreatedBy");
            DropColumn("dbo.tbl_CommunicationOfficeDoc", "UpdateDate");
            DropColumn("dbo.tbl_CommunicationOfficeDoc", "UpdateBy");
            DropColumn("dbo.tbl_CommunicationOfficeDoc", "CreatedDate");
            DropColumn("dbo.tbl_CommunicationOfficeDoc", "CreatedBy");
            DropColumn("dbo.tbl_CommonDataListItems", "UpdateDate");
            DropColumn("dbo.tbl_CommonDataListItems", "UpdateBy");
            DropColumn("dbo.tbl_CommonDataListItems", "CreatedDate");
            DropColumn("dbo.tbl_CommonDataListItems", "CreatedBy");
            DropColumn("dbo.tbl_CommonDataList", "UpdateDate");
            DropColumn("dbo.tbl_CommonDataList", "UpdateBy");
            DropColumn("dbo.tbl_CommonDataList", "CreatedDate");
            DropColumn("dbo.tbl_CommonDataList", "CreatedBy");
            DropColumn("dbo.Tbl_Comm", "UpdateDate");
            DropColumn("dbo.Tbl_Comm", "UpdateBy");
            DropColumn("dbo.Tbl_Comm", "CreatedBy");
            DropColumn("dbo.tbl_CandidatesInformationDoc", "UpdateDate");
            DropColumn("dbo.tbl_CandidatesInformationDoc", "UpdateBy");
            DropColumn("dbo.tbl_CandidatesInformationDoc", "CreatedDate");
            DropColumn("dbo.tbl_CandidatesInformationDoc", "CreatedBy");
            DropColumn("dbo.tbl_BookOfAccountsDoc", "UpdateDate");
            DropColumn("dbo.tbl_BookOfAccountsDoc", "UpdateBy");
            DropColumn("dbo.tbl_BookOfAccountsDoc", "CreatedDate");
            DropColumn("dbo.tbl_BookOfAccountsDoc", "CreatedBy");
            DropColumn("dbo.tbl_Bank_Details", "UpdateDate");
            DropColumn("dbo.tbl_Bank_Details", "UpdateBy");
            DropColumn("dbo.tbl_Bank_Details", "CreatedDate");
            DropColumn("dbo.tbl_Bank_Details", "CreatedBy");
            DropColumn("dbo.tbl_Archive", "UpdateDate");
            DropColumn("dbo.tbl_Archive", "UpdateBy");
            DropColumn("dbo.tbl_Archive", "CreatedDate");
            DropColumn("dbo.tbl_Archive", "CreatedBy");
            DropColumn("dbo.tbl_Academy", "UpdateDate");
            DropColumn("dbo.tbl_Academy", "UpdateBy");
            DropColumn("dbo.tbl_Academy", "CreatedDate");
            DropColumn("dbo.tbl_Academy", "CreatedBy");
            DropColumn("dbo.SocInsPages", "UpdateDate");
            DropColumn("dbo.SocInsPages", "UpdateBy");
            DropColumn("dbo.SocInsPages", "CreatedDate");
            DropColumn("dbo.SocInsPages", "CreatedBy");
            DropColumn("dbo.Societys", "UpdateDate");
            DropColumn("dbo.Societys", "UpdateBy");
            DropColumn("dbo.Societys", "CreatedDate");
            DropColumn("dbo.Societys", "CreatedBy");
            DropColumn("dbo.SocietyDatas", "UpdateDate");
            DropColumn("dbo.SocietyDatas", "UpdateBy");
            DropColumn("dbo.SocietyDatas", "CreatedBy");
            DropColumn("dbo.Sacraments", "UpdateDate");
            DropColumn("dbo.Sacraments", "UpdateBy");
            DropColumn("dbo.Sacraments", "CreatedDate");
            DropColumn("dbo.Sacraments", "CreatedBy");
            DropColumn("dbo.RolePermissions", "UpdateDate");
            DropColumn("dbo.RolePermissions", "UpdateBy");
            DropColumn("dbo.RolePermissions", "CreatedDate");
            DropColumn("dbo.RolePermissions", "CreatedBy");
            DropColumn("dbo.ProvinceDatas", "UpdateDate");
            DropColumn("dbo.ProvinceDatas", "UpdateBy");
            DropColumn("dbo.ProvinceDatas", "CreatedBy");
            DropColumn("dbo.NewsLetters", "UpdateDate");
            DropColumn("dbo.NewsLetters", "UpdateBy");
            DropColumn("dbo.NewsLetters", "CreatedDate");
            DropColumn("dbo.NewsLetters", "CreatedBy");
            DropColumn("dbo.MyDataCOS", "UpdateDate");
            DropColumn("dbo.MyDataCOS", "UpdateBy");
            DropColumn("dbo.MyDataCOS", "CreatedDate");
            DropColumn("dbo.MyDataCOS", "CreatedBy");
            DropColumn("dbo.MyComDataCHes", "UpdateDate");
            DropColumn("dbo.MyComDataCHes", "UpdateBy");
            DropColumn("dbo.MyComDataCHes", "CreatedDate");
            DropColumn("dbo.MyComDataCHes", "CreatedBy");
            DropColumn("dbo.GeneralCouncils", "UpdateDate");
            DropColumn("dbo.GeneralCouncils", "UpdateBy");
            DropColumn("dbo.GeneralCouncils", "CreatedDate");
            DropColumn("dbo.GeneralCouncils", "CreatedBy");
            DropColumn("dbo.GeneralateFileNoes", "UpdateDate");
            DropColumn("dbo.GeneralateFileNoes", "UpdateBy");
            DropColumn("dbo.GeneralateFileNoes", "CreatedDate");
            DropColumn("dbo.GeneralateFileNoes", "CreatedBy");
            DropColumn("dbo.FamilyDetails", "UpdateDate");
            DropColumn("dbo.FamilyDetails", "UpdateBy");
            DropColumn("dbo.FamilyDetails", "CreatedDate");
            DropColumn("dbo.FamilyDetails", "CreatedBy");
            DropColumn("dbo.ExcelSheetDatas", "UpdateDate");
            DropColumn("dbo.ExcelSheetDatas", "UpdateBy");
            DropColumn("dbo.ExcelSheetDatas", "CreatedDate");
            DropColumn("dbo.ExcelSheetDatas", "CreatedBy");
            DropColumn("dbo.DataLists2", "UpdateDate");
            DropColumn("dbo.DataLists2", "UpdateBy");
            DropColumn("dbo.DataLists2", "CreatedDate");
            DropColumn("dbo.DataLists2", "CreatedBy");
            DropColumn("dbo.DataLists", "UpdateDate");
            DropColumn("dbo.DataLists", "UpdateBy");
            DropColumn("dbo.DataLists", "CreatedDate");
            DropColumn("dbo.DataLists", "CreatedBy");
            DropColumn("dbo.DataListItems2", "UpdateDate");
            DropColumn("dbo.DataListItems2", "UpdateBy");
            DropColumn("dbo.DataListItems2", "CreatedDate");
            DropColumn("dbo.DataListItems2", "CreatedBy");
            DropColumn("dbo.DataListItems", "UpdateDate");
            DropColumn("dbo.DataListItems", "UpdateBy");
            DropColumn("dbo.DataListItems", "CreatedDate");
            DropColumn("dbo.DataListItems", "CreatedBy");
            DropColumn("dbo.CounCircCommis", "UpdateDate");
            DropColumn("dbo.CounCircCommis", "UpdateBy");
            DropColumn("dbo.CounCircCommis", "CreatedDate");
            DropColumn("dbo.CounCircCommis", "CreatedBy");
            DropColumn("dbo.CongreDatas", "UpdateDate");
            DropColumn("dbo.CongreDatas", "UpdateBy");
            DropColumn("dbo.CongreDatas", "CreatedBy");
            DropColumn("dbo.CongDatas", "UpdateDate");
            DropColumn("dbo.CongDatas", "UpdateBy");
            DropColumn("dbo.CongDatas", "CreatedBy");
            DropColumn("dbo.ComOutSideDetails", "UpdateDate");
            DropColumn("dbo.ComOutSideDetails", "UpdateBy");
            DropColumn("dbo.ComOutSideDetails", "CreatedDate");
            DropColumn("dbo.ComOutSideDetails", "CreatedBy");
            DropColumn("dbo.ComOutSides", "UpdateDate");
            DropColumn("dbo.ComOutSides", "UpdateBy");
            DropColumn("dbo.ComOutSides", "CreatedDate");
            DropColumn("dbo.ComOutSides", "CreatedBy");
            DropColumn("dbo.ComHouseDetails", "UpdateDate");
            DropColumn("dbo.ComHouseDetails", "UpdateBy");
            DropColumn("dbo.ComHouseDetails", "CreatedDate");
            DropColumn("dbo.ComHouseDetails", "CreatedBy");
            DropColumn("dbo.ComHouses", "UpdateDate");
            DropColumn("dbo.ComHouses", "UpdateBy");
            DropColumn("dbo.ComHouses", "CreatedDate");
            DropColumn("dbo.ComHouses", "CreatedBy");
            DropColumn("dbo.Circulars", "UpdateDate");
            DropColumn("dbo.Circulars", "UpdateBy");
            DropColumn("dbo.Circulars", "CreatedDate");
            DropColumn("dbo.Circulars", "CreatedBy");
            DropColumn("dbo.Appointments", "UpdateDate");
            DropColumn("dbo.Appointments", "UpdateBy");
            DropColumn("dbo.Appointments", "CreatedDate");
            DropColumn("dbo.Appointments", "CreatedBy");
            DropColumn("dbo.AppointmentDatas", "UpdateDate");
            DropColumn("dbo.AppointmentDatas", "UpdateBy");
            DropColumn("dbo.AppointmentDatas", "CreatedDate");
            DropColumn("dbo.AppointmentDatas", "CreatedBy");
            DropColumn("dbo.AllProvinceRecords", "UpdateDate");
            DropColumn("dbo.AllProvinceRecords", "UpdateBy");
            DropColumn("dbo.AllProvinceRecords", "CreatedDate");
            DropColumn("dbo.AllProvinceRecords", "CreatedBy");
        }
    }
}
