// <auto-generated />
namespace Generalate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addcoumntabpermissiontbl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcoumntabpermissiontbl));
        
        string IMigrationMetadata.Id
        {
            get { return "202005151801272_addcoumntabpermissiontbl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
