// <auto-generated />
namespace Generalate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Migraion2308 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Migraion2308));
        
        string IMigrationMetadata.Id
        {
            get { return "202108231330146_Migraion2308"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
