// <auto-generated />
namespace Generalate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Tbl_Cong1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tbl_Cong1));
        
        string IMigrationMetadata.Id
        {
            get { return "202204180342426_Tbl_Cong1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
