// <auto-generated />
namespace Generalate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Temp_15_03_23 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Temp_15_03_23));
        
        string IMigrationMetadata.Id
        {
            get { return "202303151544322_Temp_15_03_23"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
