//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generalate.Models.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentContent
    {
        public int ID { get; set; }
        public Nullable<int> DocumentId { get; set; }
        public string Filename { get; set; }
        public Nullable<System.Guid> ArchivedFile { get; set; }
        public byte[] FileContent { get; set; }
        public string FileMIMEtype { get; set; }
        public string FileExtension { get; set; }
        public System.DateTime Filesendtime { get; set; }
        public string CommunityName { get; set; }
        public string Place { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string DocumentCategory { get; set; }
        public string DocumentSubCategory { get; set; }
        public string Year { get; set; }
        public Nullable<System.DateTime> Filesentdate { get; set; }
    }
}
