//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generalate.Models.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentField
    {
        public int ID { get; set; }
        public string CommunityName { get; set; }
        public string Place { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string DocumentCategory { get; set; }
        public string DocumentSubCategory { get; set; }
        public Nullable<int> Year { get; set; }
        public string DocumentName { get; set; }
    }
}
