//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generalate.Models.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class InboxEmailAttachment
    {
        public System.Guid InboxEmailID { get; set; }
        public string Filename { get; set; }
        public byte[] Attachment { get; set; }
        public System.Guid ID { get; set; }
    
        public virtual InboxEmail InboxEmail { get; set; }
    }
}
