//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generalate.Models.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class InboxEmail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InboxEmail()
        {
            this.InboxEmailAttachments = new HashSet<InboxEmailAttachment>();
        }
    
        public string EmailUid { get; set; }
        public string FromAddress { get; set; }
        public string ToAddress { get; set; }
        public string CCAddress { get; set; }
        public string BCCAddress { get; set; }
        public Nullable<System.DateTime> EmailDate { get; set; }
        public string Subject { get; set; }
        public byte[] Body { get; set; }
        public Nullable<int> MailType { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid ID { get; set; }
        public string asciiBody { get; set; }
        public string utfBody { get; set; }
        public string utfsBody { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InboxEmailAttachment> InboxEmailAttachments { get; set; }
    }
}
