//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generalate.Models.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class PArchiveFieldValue
    {
        public int ID { get; set; }
        public int FieldId { get; set; }
        public string FieldValue { get; set; }
        public Nullable<int> ParentFieldId { get; set; }
        public string Fieldname { get; set; }
    }
}
