//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generalate.Models.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalDocumentContent
    {
        public int ID { get; set; }
        public string Filename { get; set; }
        public Nullable<System.Guid> ArchivedFile { get; set; }
        public byte[] FileContent { get; set; }
        public string FileMIMEtype { get; set; }
        public string FileExtension { get; set; }
        public System.DateTime Filesendtime { get; set; }
        public string Name { get; set; }
        public string Adhar_No { get; set; }
        public Nullable<System.DateTime> FileSentdate { get; set; }
        public string PANCopy { get; set; }
        public string MemberID { get; set; }
        public string PDocumentCategory { get; set; }
        public string PDocumentSubCategory { get; set; }
        public string PYear { get; set; }
    }
}
