//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generalate.Models.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ParisInstitutionDetails
    {
        public int Id { get; set; }
        public string MyId { get; set; }
        public string Name { get; set; }
        public string Place { get; set; }
        public string Type { get; set; }
        public string YearOfEstablacement { get; set; }
        public string Address { get; set; }
        public string FileName { get; set; }
        public string ParisId { get; set; }
        public string SocietyId { get; set; }
        public string Telephone { get; set; }
        public string InstitutionType { get; set; }
        public string TypesOfReg { get; set; }
        public string RegistrationNo { get; set; }
        public string DiscCode { get; set; }
        public string TypeCode { get; set; }
        public string RegIdCode { get; set; }
        public string BEORegCode { get; set; }
        public string CertificationCode { get; set; }
        public string OtherDoc { get; set; }
        public string Doc1 { get; set; }
        public string Doc2 { get; set; }
        public string CreatedDate { get; set; }
        public string Tial { get; set; }
        public string Date { get; set; }
        public string Description { get; set; }
        public string Country { get; set; }
        public string EmailId { get; set; }
        public string DisSec { get; set; }
        public string ProvinceName { get; set; }
        public string ActiveCkeck { get; set; }
        public string Vission { get; set; }
        public string Mission { get; set; }
        public string Activities { get; set; }
        public string Diocese { get; set; }
        public string Enterby { get; set; }
        public string EnterbyName { get; set; }
        public string EnterbyId { get; set; }
        public string CreatedBy { get; set; }
        public string UpdateBy { get; set; }
        public string UpdateDate { get; set; }
        public string History { get; set; }
        public string Remarks { get; set; }
    }
}
