//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generalate.Models.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SMSContent
    {
        public int ContentId { get; set; }
        public string Feast { get; set; }
        public string Content { get; set; }
        public string Status { get; set; }
        public string Spare { get; set; }
    }
}
