//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generalate.Models.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DailySms
    {
        public long SmsId { get; set; }
        public string Name { get; set; }
        public string BirthDate { get; set; }
        public string OrdinationDate { get; set; }
        public string FeastDate { get; set; }
        public string Mobile { get; set; }
        public string Status { get; set; }
        public string Spare1 { get; set; }
        public string Spare2 { get; set; }
        public string Spare3 { get; set; }
    }
}
