//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generalate.Models.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EmailAttachement
    {
        public string attchedfilename { get; set; }
        public byte[] FileContent { get; set; }
        public string FileMIMEtype { get; set; }
        public string FileExtension { get; set; }
        public System.DateTime Filesendtime { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid FileUniqueId { get; set; }
        public Nullable<System.Guid> EmailUniqueId { get; set; }
    
        public virtual tbl_Emaildata tbl_Emaildata { get; set; }
    }
}
