//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generalate.Models.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Emaildata
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Emaildata()
        {
            this.tbl_EmailAttachement = new HashSet<tbl_EmailAttachement>();
        }
    
        public string EmailSubject { get; set; }
        public string EmailBody { get; set; }
        public string ToAddress { get; set; }
        public string Admin { get; set; }
        public System.DateTime Emailsentdate { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid EmailUniqueId { get; set; }
        public string CCAddress { get; set; }
        public string BCCAddress { get; set; }
        public Nullable<bool> IsImportant { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_EmailAttachement> tbl_EmailAttachement { get; set; }
    }
}
