using Generalate.Helpers;
using Generalate.Models;
using System;
using System.Linq;
using System.Web.Mvc;

namespace Generalate.Controllers
{
    [CustomAuthenticationFilter]
    public class SocityController : Controller
    {
        // GET: Socity

        GeneralDBContext dbcont = new GeneralDBContext();

        public ActionResult SocityAdministration()
        {
            return View();
        }

        public ActionResult SocityMain()
        {
            var allMembers = dbcont.tbl_PersonalDetails.ToList();
            ViewBag.allMembers = allMembers;
            return View();
        }

        public ActionResult PopDetails()
        {
            return View();
        }

       
        public ActionResult Institution()
        {
            return View();
        }
        public ActionResult AddInstMember()
        {
            return View();
        }

        public JsonResult GetAutoGeneratedMemberId()
        {
            var query = (from c in dbcont.tbl_InstitutionFinal
                         select new { c.InstitutionId }).Count() + 1;

            string id = string.Format("{0:000}", query);

            return Json(id, JsonRequestBehavior.AllowGet);
        }


        public JsonResult Add(tbl_Bank_Details general)
        {
            try
            {
                dbcont.tbl_Bank_Details.Add(general);
                dbcont.SaveChanges();
                return Json("Success");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return Json("Failed");
            }
        }

        public JsonResult Addso(tbl_Socityadd general)
        {
            try
            {
                dbcont.tbl_Socityadd.Add(general);
                dbcont.SaveChanges();
                return Json("Success");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return Json("Failed");
            }
        }


        public ActionResult AddSociety(Societys general)
        {
            try
            {
                dbcont.Societys.Add(general);
                dbcont.SaveChanges();
            }
#pragma warning disable CS0168 // The variable 'ex' is declared but never used
            catch (Exception ex)
#pragma warning restore CS0168 // The variable 'ex' is declared but never used
            {
               
            }
            return RedirectToAction("SocityMain");
        }


    }
}